# One Hot Encoding

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

# Örnek dökümanlar
documents = [
    "Bu bir örnek dökümandır.",
    "Örnek dökümanları one-hot encoding'e dönüştürme işlemi.",
    "One-hot encoding için scikit-learn kullanılıyor.",
    "Her bir kelimenin varlık veya yokluğunu gösteren bir vektör elde edilecek."
]

# CountVectorizer'ı kullanarak one-hot encoding'i gerçekleştirin
vectorizer = CountVectorizer(binary=True)
one_hot_matrix = vectorizer.fit_transform(documents)

# One-hot encoding matrisini ekrana yazdırın
print("One-hot Encoding Matrisi:")
print(one_hot_matrix.toarray())

# Kelime indekslerini ekrana yazdırın
print("Kelime İndeksleri:")
print(vectorizer.vocabulary_)


One-hot Encoding Matrisi:
[[1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0]
 [1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1 0]]
Kelime İndeksleri:
{'bu': 1, 'bir': 0, 'örnek': 22, 'dökümandır': 2, 'dökümanları': 3, 'one': 16, 'hot': 10, 'encoding': 7, 'dönüştürme': 4, 'işlemi': 12, 'için': 11, 'scikit': 17, 'learn': 15, 'kullanılıyor': 14, 'her': 9, 'kelimenin': 13, 'varlık': 18, 'veya': 20, 'yokluğunu': 21, 'gösteren': 8, 'vektör': 19, 'elde': 6, 'edilecek': 5}


# CountVecdtor

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

# Örnek dökümanlar
documents = [
    "Bu bir örnek dökümandır.",
    "Örnek dökümanları CountVectorizer'a dönüştürme işlemi.",
    "CountVectorizer'ı kullanarak bir kelime sayım matrisi elde edeceğiz.",
    "Her bir kelimenin döküman içinde kaç kez geçtiğini gösteren bir matris."
]

# CountVectorizer'ı kullanarak dökümanları bir kelime sayım matrisine dönüştürün
vectorizer = CountVectorizer()
word_count_matrix = vectorizer.fit_transform(documents)

# Matrisi ekrana yazdırın
print("Kelime Sayım Matrisi:")
print(word_count_matrix.toarray())

# Kelime indekslerini ekrana yazdırın
print("Kelime İndeksleri:")
print(vectorizer.vocabulary_)



Kelime Sayım Matrisi:
[[1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0]
 [2 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0]]
Kelime İndeksleri:
{'bu': 1, 'bir': 0, 'örnek': 22, 'dökümandır': 4, 'dökümanları': 5, 'countvectorizer': 2, 'dönüştürme': 6, 'işlemi': 13, 'kullanarak': 18, 'kelime': 15, 'sayım': 21, 'matrisi': 20, 'elde': 8, 'edeceğiz': 7, 'her': 11, 'kelimenin': 16, 'döküman': 3, 'içinde': 12, 'kaç': 14, 'kez': 17, 'geçtiğini': 9, 'gösteren': 10, 'matris': 19}


# TF-IDF

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Örnek dökümanlar
documents = [
    "Bu bir örnek dökümandır.",
    "Örnek dökümanları TF-IDF vektörlerine dönüştürme işlemi.",
    "TF-IDF vektörleri, her kelimenin belirli bir belgedeki önemini ölçer.",
    "Her bir kelimenin TF-IDF vektörü, o kelimenin belirli bir belgedeki önemini temsil eder."
]

# TfidfVectorizer'ı kullanarak dökümanları TF-IDF matrisine dönüştürün
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

# Matrisi ekrana yazdırın
print("TF-IDF Matrisi:")
print(tfidf_matrix.toarray())

# Kelime indekslerini ekrana yazdırın
print("Kelime İndeksleri:")
print(vectorizer.vocabulary_)


TF-IDF Matrisi:
[[0.         0.         0.36674667 0.57457953 0.57457953 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.4530051 ]
 [0.         0.         0.         0.         0.         0.42888787
  0.42888787 0.         0.         0.27375357 0.42888787 0.
  0.         0.27375357 0.         0.42888787 0.         0.
  0.         0.33814012]
 [0.31336062 0.31336062 0.25369243 0.         0.         0.
  0.         0.         0.31336062 0.25369243 0.         0.31336062
  0.         0.25369243 0.39745821 0.         0.         0.39745821
  0.31336062 0.        ]
 [0.24427407 0.24427407 0.39552182 0.         0.         0.
  0.         0.30983068 0.24427407 0.19776091 0.         0.48854814
  0.30983068 0.19776091 0.         0.         0.30983068 0.
  0.24427407 0.        ]]
Kelime İndeksleri:
{'bu': 3, 'bir': 2, 'örnek': 19, 'dökümandır': 4, 'dökümanları': 5, 'tf': 13, 'idf': 9, 'vektörlerine': 15, 'dön

# Co-Occurance

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import coo_matrix
import numpy as np

# Örnek dökümanlar
documents = [
    "Bu bir örnek dökümandır.",
    "Örnek dökümanları co-occurrence matrisine dönüştürme işlemi.",
    "Co-occurrence matrisi, belirli kelimelerin bir arada geçme sıklığını gösterir.",
    "Bu örnekte, co-occurrence matrisini oluşturuyoruz ve ekrana yazdırıyoruz."
]

# CountVectorizer'ı kullanarak dökümanları bir kelime sayım matrisine dönüştürün
vectorizer = CountVectorizer(binary=True)
word_count_matrix = vectorizer.fit_transform(documents)

# Kelime sayım matrisini co-occurrence matrisine dönüştürün
co_occurrence_matrix = word_count_matrix.T.dot(word_count_matrix)

# Diagonal değerleri 0 yapın (kelimenin kendi kendisi ile olan geçişleri)
co_occurrence_matrix.setdiag(0)

# coo_matrix'e dönüştürün
co_occurrence_matrix = coo_matrix(co_occurrence_matrix)

# Matrisi ekrana yazdırın
print("Co-occurrence Matrisi:")
print(co_occurrence_matrix.toarray())

# Kelime indekslerini ekrana yazdırın
print("Kelime İndeksleri:")
print(vectorizer.vocabulary_)



Co-occurrence Matrisi:
[[0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 1 0 0 0 0]
 [1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 1 0 0 1 0]
 [0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1]
 [1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 0 1]
 [1 1 1 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0]
 [1 1 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0]
 [1 1 1 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0]
 [1 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 0 1]
 [1 1 1 1 3 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 0 1]
 [1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 

# CBOW
Word2Vec sınıfını kullanarak CBOW modelini oluşturuyoruz. Parametreler şu şekildedir:

sentences: Eğitim için kullanılacak cümleleri içeren liste. Burada sadece tek bir cümle kullanıyoruz.
vector_size: Her kelimenin temsil edileceği vektör boyutu.
window: Tahmin edilen kelimenin etrafındaki bağlamın boyutu.
sg: Skip-gram (1) veya CBOW (0) modelini belirten parametre. Burada CBOW modelini seçtik.
min_count: Modelde yer alacak en az sayıda kelime sayısı.
workers: Eğitim için kullanılacak işçi sayısı.

In [31]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk


# Örnek bir metin
text = "Bu bir örnek cümledir. CBOW modelini oluşturmak için kullanılacaktır."

# Metni tokenlara ayırın
tokens = word_tokenize(text.lower())  # Küçük harfe çevirme işlemi

# CBOW modelini oluşturun
model_cbow = Word2Vec(sentences=[tokens], vector_size=10, window=3, sg=0, min_count=1, workers=4)

# Modeli eğitin
model_cbow.train([tokens], total_examples=1, epochs=10)

# Kelimeler arasındaki benzerlikleri kontrol edin
similar_words_cbow = model_cbow.wv.most_similar('örnek', topn=3)

# Sonuçları yazdırın
print("CBOW ile Örnek kelimenin benzer kelimeleri:")
for word, score in similar_words_cbow:
    print(f"{word}: {score}")


CBOW ile Örnek kelimenin benzer kelimeleri:
için: 0.42765650153160095
oluşturmak: 0.2944478392601013
kullanılacaktır: 0.23284997045993805


# skip gram

In [36]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk


# Örnek bir metin
text = "Bu bir örnek cümledir. Skip-gram modelini oluşturmak için kullanılacaktır."

# Metni tokenlara ayırın
tokens = word_tokenize(text.lower())  # Küçük harfe çevirme işlemi

# Skip-gram modelini oluşturun
model_skipgram = Word2Vec(sentences=[tokens], vector_size=10, window=3, sg=1, min_count=1, workers=4)

# Modeli eğitin
model_skipgram.train([tokens], total_examples=1, epochs=10)

# Kelimeler arasındaki benzerlikleri kontrol edin
similar_words_skipgram = model_skipgram.wv.most_similar('bu', topn=3)

# Sonuçları yazdırın
print("Skip-gram ile Örnek kelimenin benzer kelimeleri:")
for word, score in similar_words_skipgram:
    print(f"{word}: {score}")


Skip-gram ile Örnek kelimenin benzer kelimeleri:
skip-gram: 0.2914133667945862
için: 0.05529548600316048
modelini: 0.04264767840504646


# word2vec

In [26]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

# Örnek bir metin
text = "Bu bir örnek cümledir. Word2Vec modelini kullanarak kelime gömme vektörlerini öğreniyoruz."

# Metni tokenlara ayırın
tokens = word_tokenize(text.lower())

# Word2Vec modelini oluşturun
model = Word2Vec(sentences=[tokens], vector_size=10, window=3, sg=1, min_count=1, workers=4)

# Modeli eğitin
model.train([tokens], total_examples=1, epochs=10)

# "örnek" kelimesinin vektörünü alın
vector_example = model.wv['örnek']

# Benzer kelimeleri kontrol edin
similar_words = model.wv.most_similar('örnek', topn=3)

# Sonuçları yazdırın
print("Kelime Vektörü (örnek):", vector_example)
print("Örnek kelimenin benzer kelimeleri:")
for word, score in similar_words:
    print(f"{word}: {score}")


Kelime Vektörü (örnek): [ 0.01624836  0.00190858  0.03468794  0.00220425  0.09621963  0.05060079
 -0.08915306 -0.07035083  0.00899166  0.06398909]
Örnek kelimenin benzer kelimeleri:
kullanarak: 0.2915043830871582
vektörlerini: 0.05535745620727539
kelime: 0.0433088056743145


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Kaya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
